export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';
export const POST_USER = 'POST_USER';
export const USER_LOGIN = 'USER_LOGIN';
export const REGISTER_USER_OR_ADMIN = 'REGISTER_USER_OR_ADMIN';
export const TOGGLE_LOGIN_LOGOUT = 'TOGGLE_LOGIN_LOGOUT';
export const FETCH_COLLEGE = 'FETCH_COLLEGE';
export const FETCH_STATE = 'FETCH_STATE';
export const FETCH_COLLEGE_SUCCESS = 'FETCH_COLLEGE_SUCCESS';
export const FETCH_STATE_SUCCESS = 'FETCH_STATE_SUCCESS';
export const PUSH_STUDENT_FORM_SUCCESS = 'PUSH_STUDENT_FORM_SUCCESS';
export const PUSH_STUDENT_FORM = 'PUSH_STUDENT_FORM';
export const COLLEGE_FORM_DATA = 'COLLEGE_FORM_DATA';

